name: <snakemake_template>
channels:
  - bioconda
  - conda-forge
dependencies:
 - snakemake=7.18.2
 - snakefmt # snakemake code formatter
 - graphviz=9.0.0 # to visualize the DAG

module load snakemake/7.18.2-foss-2020b
